[package]
name = "five-in-a-row"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd = { workspace = true }
five-in-a-row-io.workspace = true

[build-dependencies]
gmeta.workspace = true
five-in-a-row-io.workspace = true
gear-wasm-builder.workspace = true

[dev-dependencies]
gstd = { workspace = true, features = ["debug"] }
gtest.workspace = true
gclient.workspace = true
tokio.workspace = true
hex.workspace = true
gear-core.workspace = true

[features]
binary-vendor = []

